# vim:fileencoding=utf-8:foldmethod=marker

# Editor {{{
term                                xterm-kitty
editor                              nvim
shell_integration                   no-cursor
kitty_mod                           ctrl+shift
}}}

# Window {{{
enable_audio_bell                   no
remember_window_size                no
initial_window_width                1000
initial_window_height               700
placement_strategy                  center
hide_window_decorations             no
window_padding_width                5 10
window_title                        zimn@arch
# windows_logo_path                   none
scrollback_lines                    1000
wheel_scroll_multiplier             5.0
enabled_layouts                     *
sync_to_monitor                     yes
}}}

# Tabs {{{
tab_bar_min_tabs                    2
tab_bar_edge                        bottom
tab_bar_style                       powerline
tab_powerline_style                 angled
tab_title_template                  "{sup.index} {title}"
}}}

# Binds {{{

# Open new tab
map ctrl+t                          new_tab_with_cwd

# Close tab
map ctrl+w                          close_tab

# Switch tabs
map ctrl+shift+h                    previous_tab
map ctrl+shift+l                    next_tab

# Detach tab
map ctrl+shift+d										detach_tab

# rename tab
map ctrl+shift+r										set_tab_title

# Clear terminal
map ctrl+space combine : clear_terminal scrollback active : send_text normal,application \x0c

# Delete a word
map ctrl+backspace                  send_text all \x17

# Jump to beginning and end of word
map ctrl+h                          send_text all \x1b\x62
map ctrl+l                          send_text all \x1b\x66
}}}

# Cursor and mouse  {{{
cursor_shape                        underline
cursor_blink_interval               0.0
cursor_stop_blinking_after          5.0
url_style                           single
url_prefixes                        http https file ftp irc mailto news git
detect_urls                         yes
}}}

# Fonts {{{
font_family                         JetBrains Mono Nerd Font
bold_font                           auto
italic_font                         CartographCF Italic
font_size                           12.0
}}}

# Colorscheme {{{
## name: Catppuccin
## author: Pocco81 (https://github.com/Pocco81)
## license: MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/catppuccin.conf
## blurb: Soothing pastel theme for the high-spirited!

# The basic colors
foreground              #EBDBB2
background              #1D2022
selection_foreground    #EBDBB2
selection_background    #3C3C3C

# Cursor colors
cursor                  #D5C4A1
cursor_text_color       #1E1E2E

# URL underline color when hovering with mouse
url_color               #F5E0DC

# kitty window border colors
active_border_color     #C9CBFF
inactive_border_color   #575268
bell_border_color       #FAE3B0

# OS Window titlebar colors
wayland_titlebar_color background

#: Tab bar colors
active_tab_foreground         #1D2022
active_tab_background         #A89984
inactive_tab_foreground       #A89984
inactive_tab_background       #2A2B2D
tab_bar_background            #1D2022
# Colors for marks (marked text in the terminal)

mark1_foreground #282828
mark1_background #458588
mark2_foreground #282828
mark2_background #B16386
mark3_foreground #1E1E2E
mark3_background #458588

#: The 16 terminal colors

#: black
color0 #1D2022
color8 #4B4B4B

#: red
color1 #CC241D
color9 #CC241D

#: green
color2  #98971A
color10 #98971A

#: yellow
color3  #D79921
color11 #D79921

#: blue
color4  #458588
color12 #458588

#: magenta
color5  #B16286
color13 #B16286

#: cyan
color6  #689D6A
color14 #689D6A

#: white
color7  #A89984
color15 #A89984
}}}
